// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	AUTH_SECRET: string;
	AUTH_RESEND_KEY: string;
	AUTH_EMAIL_FROM: string;
	AUTH_URL: string;
	DB: D1Database;
	ASSETS: Fetcher;
}
